ekf_filter_node:
  ros__parameters:
    frequency: 7.0
    sensor_timeout: 0.2
    two_d_mode: true
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint

    odom0: odom/unfiltered
    odom0_config: [false, false, false,
                   false, false, false,
                   true, true, false,
                   false, false, false,
                   false, false, true]

    imu0: /imu/data_filtered
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, true,
                  false, false, false]

    imu0_differential: false
    imu0_relative: true

    use_control: false
    publish_acceleration: false
    debug: false